#!/bin/bash

mkdir -p $HOME/.local/share/icons/hicolor/scalable/apps && cp $APPDIR/dolphin-emu.svg $HOME/.local/share/icons/hicolor/scalable/apps

GITVER=`wget -qO- https://www.github.com/qurious-pixel/dolphin/releases/tag/continuous | grep qurious-pixel/dolphin/commit/ | cut -d '"' -f 2 | cut -d '/' -f 5 | awk '!x[$0]++'` 
APPVER=`cat $APPDIR/version.txt`

if [ "$GITVER" = "$APPVER" ]; then
	QT_QPA_PLATFORM=xcb $APPDIR/usr/bin/dolphin-emu
else
	$APPDIR/update.sh
fi
