name: Dolphin-AppImage

on: 
  push:
  workflow_dispatch:
  schedule:
    #- cron: "0 0 * * 1" 
    - cron: "1 22 * * 2"

jobs:
  beta-run-check:
    runs-on: ubuntu-22.04
    #outputs:
    #    BETAUPDATE: ${{ steps.hasNextVersionOutput.outputs.hasNextVersion }}
    steps:
    - name: Beta Run Check
      run: |
        export RUNHASH=$(curl -sSfL https://github.com/qurious-pixel/dolphin/releases/tag/beta | grep '<tt>' | awk '{print $NF}' | grep -E -o 'commit.{41}' | sed 's/commit\///g')
        export BETAHASH=$(curl -sSfL https://dolphin-emu.org/update/latest/beta/ | jq .hash | tr -d '"')
        echo "RUNHASH is $RUNHASH"
        echo "BETAHASH is $BETAHASH"
        if [[ $RUNHASH != $BETAHASH ]]; then 
        	echo "BETAUPDATE=false" >> $GITHUB_OUTPUT
        else 
        	#echo "Updating..."
         echo "BETAUPDATE=true" >> $GITHUB_OUTPUT
        fi
        
  dolphin-appimage:
    if: always() && needs.beta-run-check.outputs.BETAUPDATE == 'true'
    name: dolphin beta bundled as appimage
    runs-on: ubuntu-20.04
    needs: beta-run-check
    env:
      yaqti: 6.6.1
    steps:

    - name: Get Beta Hash
      run: |
        export BETAHASH=$(curl -sSfL https://dolphin-emu.org/update/latest/beta/ | jq .hash | tr -d '"')
        echo "BETAHASH=$BETAHASH" >> $GITHUB_ENV
        echo "$BETAHASH"
    - name: Checkout Upstream Repo
      uses: actions/checkout@v4
      with:
        repository: dolphin-emu/dolphin
        ref: ${{ env.BETAHASH }}
        
  dolphin-appimage-2:
    name: dolphin release bundled as appimage
    runs-on: ubuntu-20.04
    steps:
    - name: Get Release Run
      run: |
        echo "Running Well"
